version: '3'
services:
     web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/rails_test
        depends_on:
            - db
     db:
       image: mysql:5.7
       volumes:
            - ./mysql:/var/lib/mysql
       environment:
            MYSQL_ROOT_PASSWORD: 'password'
